### ISSUE TITLE
Landing Page Checklist

### ISSUE THREAD

**Issue by nikolasklein** [Shopify/polaris-in-sketch#22]
[InVision Link](https://shopify.invisionapp.com/share/JVEJ1OWXA#/264649746_Homepage)

[Related Pull Request #1131](https://github.com/Shopify/polaris-styleguide/pull/1131)

-----

#### checklist
- [x] find a solution for the floating issue of the screenshot mock (looks weird on small screens)
- [x] add the new url to sitemap.json
- [x] disable the sub sections on the side?
- [x] add tracking to the html link `data-event-label="Download Telescope" data-event-category="Inline Link"`
- [x] on the homepage we should not link directly to the download, but to the page itself for more info
- [x] add the correct illustration in the top download link
- [x] update the icon in the navigation
- [x] update the icon on the homepage
- [x] update the download links
  - [x] big button link
  - [x] text link further down the page
  - [x] link to the github repo
-----

- [x] Content → Selene
- [x] Technical Integration into the Polaris site → Andre
- [x] Illustration → Illustration team
